### ISSUE TITLE
Incorrect handling of oddly executing asyncwriters

### ISSUE THREAD

**Issue by mlrawlings** [marko-js/async-writer#5]
More details on the issue:
https://tonicdev.com/mlrawlings/57be0a56ba6f4b1600c5e74d

**Comment by CNManning** [comment]
Now that this has been merged would it be possible to publish the new version to npm? We have struck this bug, and are currently having to use a manually altered shrinkwrap.json file to force marko to use the fixed version from github.

**Comment by mlrawlings** [comment]
@CNManning I've publish a new version for this module: `async-writer@2.0.0`.  While this update maintained the same external API, the internals have completely been rewritten and there was at least one module that was using some of those internals - thus the major version bump.  However, I also published new patch versions of `marko` and `raptor-renderer` that have their dependencies updated to `async-writer@2.0.0` so you should be able to reinstall `marko` and `marko-widgets` to pick up these latest dependencies.
